<?php
return [
    'Cagliari Calcio' => [
        'shirt-team' => [
            'cag-away' => 'Cagliari-Away-Front.png',
            'cag-home' => 'Cagliari-Home-Front.png',
            'cag-third' => 'Cagliari-Third-Front.png',
        ],
        'player-team' => [
            '1-Radunović',
            '3-Goldaniga',
            '4-Dossena',
            '5-Mancosu',
            '6-Rog',
            '8-Nández',
            '9-Lapadula',
            '10-Viola',
            '12-Lolic',
            '14-Deiola',
            '15-Altare',
            '16-Carboni',
            '18-Aresti',
            '19-Millico',
            '20-Pereiro',
            '22-Ciocci',
            '23-Lella',
            '24-Capradossi',
            '25-Falco',
            '27-Barreca',
            '28-Zappa',
            '29-Makoumbou',
            '30-Pavoletti',
            '33-Obert',
            '39-Kourfalidis',
            '77-Luvumbo',
            '80-Delpupo',
            '99-Di Pardo',
        ]
    ],
    'US Catanzaro' => [
        'shirt-team' => [
            'cat-away' => 'EYE-GAME---Catanzaro-Away-Front.png',
            'cat-home' => 'EYE-GAME---Catanzaro-Home-Front.png',
            'cat-third' => 'EYE-GAME---Catanzaro-Third-Front.png',
        ],
        'player-team' => [
            '5-Martinelli',
            '13-Fazio',
            '14-Scognamillo',
            '23-Brighenti',
            '44-Gatti',
            '45-Mule',
            '91-Megna',
            '1-Fulignati',
            '12-Rizzuto',
            '16-Sala',
            '9-Iemmello',
            '10-Bombagi',
            '21-Curcio',
            '28-Biasci',
            '30-Viotti',
            '99-Cianci',
            '3-Tentardini',
            '6-Welbeck',
            '7-Rolando',
            '8-Verna',
            '18-Ghion',
            '20-Pontisso',
            '24-Sounas',
            '27-Vandeputte',
            '77-Katseris',
            '88-Cinelli',
            '92-Šitum',
        ]
    ],
    'Pro Vercelli 1982' => [
        'shirt-team' => [
            'ver-away' => 'EYE-GAME---Pro-Vercelli-Away-Front.png',
            'ver-home' => 'EYE-GAME---Pro-Vercelli-Home-Front.png',
        ],
        'player-team' => [
            '1-Valentini',
            '2-Masi',
            '3-Gentile',
            '4-Cristini',
            '5-Perrota',
            '6-Corradini',
            '7-Mustacchio',
            '8-Emmanuelo',
            '10-Comi',
            '11-Gatto',
            '12-Rizzo',
            '17-Iotti',
            '20-Louati',
            '21-Renault',
            '23-Calvano',
            '27-Macchioni',
            '29-Iezzi',
            '30-Vergara',
            '32-Anastio',
            '33-Silvestro',
            '38-Arrighini',
            '40-Guindo',
            '94-Saco',
            '99-Della Morte',
        ]
    ],
    'SS Turris' => [
        'shirt-team' => [
            'tur-away' => 'EYE-GAME---Turris-Away-Front.png',
            'tur-home' => 'EYE-GAME---Turris-Home-Front.png',
        ],
        'player-team' => [
            '4-Acquadro',
            '8-Ardizzone',
            '6-Boccia',
            '1-Donini',
            '7-Ercolano',
            '9-Santaniello',
            '5-Taugourdeau',
            '2-Vitiello',
            '3-Frascatore',
            '24-Aquino',
            '31-Contessa',
            '14-Di Franco',
            '21-Di nuncio',
            '77-Fasolino',
            '30-Finardi',
            '88-Gallo',
            '10-Giannone',
            '15-Haoudi',
            '20-Invernizzi',
            '11-Leonetti',
            '91-Longo',
            '19-Maniero',
            '16-Manzi',
            '17-Nocerino',
            '33-Perina',
            '18-Stampete',
            '23-Varutti',
        ]
    ],
    'Olbia Calcio' => [
        'shirt-team' => [
            'obl-away' => 'EYE-GAME---Olbia-Away-Front.png',
            'obl-home' => 'EYE-GAME---Olbia-Home-Front.png',
            'obl-third' => 'EYE-GAME---Olbia-Third-Front.png',
        ],
        'player-team' => [
            '1-Gelmi',
            '2-Renault',
            '3-La Rosa',
            '5-Bellodi',
            '6-Incerti',
            '7-Occhioni',
            '8-Palesi',
            '10-Ragatzu',
            '11-Babbi',
            '13-Brignani',
            '15-Zanchetta',
            '16-Boganini',
            '18-Nanni',
            '19-Travaglini',
            '20-Gabrieli',
            '21-Biancu',
            '22-Der Want',
            '25-Emerson',
            '27-Fabbri',
            '30-Sanna',
            '32-Contini',
            '33-Secci',
            '38-Finocci',
            '58-Minala',
            '76-König',
            '79-Sueva',
        ]
    ],
    'Atletico Lusaka' => [
        'shirt-team' => [
            'lus-away' => 'EYE-GAME---Atletico-Lusaka-Away-Front.png',
            'lus-home' => 'EYE-GAME---Atletico-Lusaka-Home-Front.png',
        ],
        'player-team' => [
            '1-Iford',
            '2-Thomas',
            '3-Teddy',
            '4-Mphande',
            '5-Gift Siame',
            '6-Chichi',
            '7-Kingston',
            '8-Abel',
            '9-Desmond',
            '10-Bubu',
            '11-Fredrick',
            '12-Timothy',
            '13-Lloyd',
            '14-Tryson',
            '15-Nana',
            '16-Lawrence',
            '17-Julius',
            '18-Gilbert',
            '19-Tapiwa',
            '20-Majapa',
            '21-Benjamine',
            '22-Abraham',
            '23-Ackim',
            '24-Noah',
            '25-Liteta',
            '26-Kelvin',
            '27-Healings',
            '28-Chalo',
            '29-Marcel',
            '30-Malaya',
            '31-Chris',
            '32-Bruce',
        ]
    ],
    'Taranto' => [
        'shirt-team' => [
            // 'tar-away' => 'EYE-GAME---Taranto-Away-Front.png',
            'tar-home' => 'EYE-GAME---Taranto-Home-Front.png',
        ],
        'player-team' => [
            '3-Ferrara',
            '4-Antonini',
            '5-Provenzano',
            '6-Manetta',
            '7-Semprini',
            '8-Colurciello',
            '9-Nocciolini',
            '0-Labriola',
            '1-Crecco',
            '4-Bifulco',
            '6-Fontana',
            '7-Citarella',
            '9-Sciacca',
            '1-Mazza',
            '4-Evangelisti',
            '7-Formiconi',
            '9-Rossetti',
            '8-Finocchi',
            '0-Canalicchio',
            '2-Mastromonaco',
            '7-Boccadamo',
            '1-Tommasini',
            '6-Romano',
            '5-Marini',
            '0-Alessandra',
            '6-Vannucchi',
            '1-Loliva',
            '3-Caputo',
        ]
    ]
];
